In [1]:
print('Hello')

Hello

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/Users/dhrutikkhunt/Downloads/orders_return.csv')

In [4]:
df

,order_id,customer_id,order_date,region,category,quantity,unit_price,discount,payment_type,campaign_flag,order_value,returned
0,1,103,2022-11-01,North,Skincare,4,227.69,0,Card,1,910.76,1
1,2,271,2023-03-05,North,Haircare,1,317.61,10,Card,0,285.85,0
2,3,107,2023-04-22,North,Clothing,3,246.09,0,Wallet,0,738.27,0
3,4,72,2022-10-13,East,Haircare,1,137.58,5,Card,0,130.70,0
4,5,189,2022-05-24,East,Skincare,4,245.81,0,Card,0,983.24,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,215,2023-07-15,West,Electronics,1,106.55,0,Card,1,106.55,1
996,997,211,2023-04-28,South,Skincare,1,219.37,0,Card,0,219.37,0
997,998,32,2022-04-18,West,Haircare,1,240.10,0,Wallet,1,240.10,0
998,999,158,2022-08-14,South,Oralcare,3,218.19,15,UPI,0,556.38,0
999,1000,285,2023-11-04,South,Clothing,1,155.28,0,Wallet,1,155.28,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   order_date     1000 non-null   object
 3   region         1000 non-null   object
 4   category       1000 non-null   object
 5   quantity       1000 non-null   int64
 6   unit_price     1000 non-null   float64
 7   discount       1000 non-null   int64
 8   payment_type   1000 non-null   object
 9   campaign_flag  1000 non-null   int64
 10  order_value    1000 non-null   float64
 11  returned       1000 non-null   int64
dtypes: float64(2), int64(6), object(4)
memory usage: 93.9+ KB

In [6]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   order_date     1000 non-null   datetime64[ns]
 3   region         1000 non-null   object
 4   category       1000 non-null   object
 5   quantity       1000 non-null   int64
 6   unit_price     1000 non-null   float64
 7   discount       1000 non-null   int64
 8   payment_type   1000 non-null   object
 9   campaign_flag  1000 non-null   int64
 10  order_value    1000 non-null   float64
 11  returned       1000 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(6), object(3)
memory usage: 93.9+ KB

In [8]:
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['day']=df['order_date'].dt.day

In [9]:
df

,order_id,customer_id,order_date,region,category,quantity,unit_price,discount,payment_type,campaign_flag,order_value,returned,year,month,day
0,1,103,2022-11-01,North,Skincare,4,227.69,0,Card,1,910.76,1,2022,11,1
1,2,271,2023-03-05,North,Haircare,1,317.61,10,Card,0,285.85,0,2023,3,5
2,3,107,2023-04-22,North,Clothing,3,246.09,0,Wallet,0,738.27,0,2023,4,22
3,4,72,2022-10-13,East,Haircare,1,137.58,5,Card,0,130.70,0,2022,10,13
4,5,189,2022-05-24,East,Skincare,4,245.81,0,Card,0,983.24,1,2022,5,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,215,2023-07-15,West,Electronics,1,106.55,0,Card,1,106.55,1,2023,7,15
996,997,211,2023-04-28,South,Skincare,1,219.37,0,Card,0,219.37,0,2023,4,28
997,998,32,2022-04-18,West,Haircare,1,240.10,0,Wallet,1,240.10,0,2022,4,18
998,999,158,2022-08-14,South,Oralcare,3,218.19,15,UPI,0,556.38,0,2022,8,14
999,1000,285,2023-11-04,South,Clothing,1,155.28,0,Wallet,1,155.28,0,2023,11,4

In [10]:
df.drop('order_date',axis=1,inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   region         1000 non-null   object
 3   category       1000 non-null   object
 4   quantity       1000 non-null   int64
 5   unit_price     1000 non-null   float64
 6   discount       1000 non-null   int64
 7   payment_type   1000 non-null   object
 8   campaign_flag  1000 non-null   int64
 9   order_value    1000 non-null   float64
 10  returned       1000 non-null   int64
 11  year           1000 non-null   int32
 12  month          1000 non-null   int32
 13  day            1000 non-null   int32
dtypes: float64(2), int32(3), int64(6), object(3)
memory usage: 97.8+ KB

In [12]:
df['unit_price']=df['unit_price'].astype('int64')

In [13]:
df['order_value']=df['order_value'].astype('int64')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   region         1000 non-null   object
 3   category       1000 non-null   object
 4   quantity       1000 non-null   int64
 5   unit_price     1000 non-null   int64
 6   discount       1000 non-null   int64
 7   payment_type   1000 non-null   object
 8   campaign_flag  1000 non-null   int64
 9   order_value    1000 non-null   int64
 10  returned       1000 non-null   int64
 11  year           1000 non-null   int32
 12  month          1000 non-null   int32
 13  day            1000 non-null   int32
dtypes: int32(3), int64(8), object(3)
memory usage: 97.8+ KB

In [85]:
df

,order_id,customer_id,region,category,quantity,unit_price,discount,payment_type,campaign_flag,order_value,returned,year,month,day
0,1,103,North,Skincare,4,227,0,Card,1,910,1,2022,11,1
1,2,271,North,Haircare,1,317,10,Card,0,285,0,2023,3,5
2,3,107,North,Clothing,3,246,0,Wallet,0,738,0,2023,4,22
3,4,72,East,Haircare,1,137,5,Card,0,130,0,2022,10,13
4,5,189,East,Skincare,4,245,0,Card,0,983,1,2022,5,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,215,West,Electronics,1,106,0,Card,1,106,1,2023,7,15
996,997,211,South,Skincare,1,219,0,Card,0,219,0,2023,4,28
997,998,32,West,Haircare,1,240,0,Wallet,1,240,0,2022,4,18
998,999,158,South,Oralcare,3,218,15,UPI,0,556,0,2022,8,14
999,1000,285,South,Clothing,1,155,0,Wallet,1,155,0,2023,11,4

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()

In [17]:
for col in df.columns:
    if df[col].dtype=='object':
        df[col]=le.fit_transform(df[col])

In [18]:
df

,order_id,customer_id,region,category,quantity,unit_price,discount,payment_type,campaign_flag,order_value,returned,year,month,day
0,1,103,1,5,4,227,0,1,1,910,1,2022,11,1
1,2,271,1,2,1,317,10,1,0,285,0,2023,3,5
2,3,107,1,0,3,246,0,3,0,738,0,2023,4,22
3,4,72,0,2,1,137,5,1,0,130,0,2022,10,13
4,5,189,0,5,4,245,0,1,0,983,1,2022,5,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,215,3,1,1,106,0,1,1,106,1,2023,7,15
996,997,211,2,5,1,219,0,1,0,219,0,2023,4,28
997,998,32,3,2,1,240,0,3,1,240,0,2022,4,18
998,999,158,2,4,3,218,15,2,0,556,0,2022,8,14
999,1000,285,2,0,1,155,0,3,1,155,0,2023,11,4

In [19]:
X=df.drop('returned',axis=1)
y=df['returned']

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [22]:
df.head()

,order_id,customer_id,region,category,quantity,unit_price,discount,payment_type,campaign_flag,order_value,returned,year,month,day
0,1,103,1,5,4,227,0,1,1,910,1,2022,11,1
1,2,271,1,2,1,317,10,1,0,285,0,2023,3,5
2,3,107,1,0,3,246,0,3,0,738,0,2023,4,22
3,4,72,0,2,1,137,5,1,0,130,0,2022,10,13
4,5,189,0,5,4,245,0,1,0,983,1,2022,5,24

In [23]:
X_train.head()

,order_id,customer_id,region,category,quantity,unit_price,discount,payment_type,campaign_flag,order_value,year,month,day
734,735,14,1,5,1,102,15,2,0,87,2022,9,18
575,576,28,3,2,1,139,0,2,0,139,2023,5,10
192,193,144,0,2,2,147,0,3,0,294,2023,4,23
588,589,82,2,5,2,232,10,1,1,417,2023,7,7
469,470,233,1,5,1,226,15,0,0,192,2022,7,11

In [24]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [25]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [28]:
from sklearn.svm import SVC

svm = SVC(probability=True, random_state=42)

svm.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [30]:
svm_pred = svm.predict(X_test)
svm_prob = svm.predict_proba(X_test)

In [32]:
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix

print("Accuracy:", accuracy_score(y_test, svm_pred)*100)
print("Log Loss:", log_loss(y_test, svm_prob))
print("Confusion Matrix:")
print(confusion_matrix(y_test, svm_pred))

Accuracy: 89.0
Log Loss: 0.3468592640743662
Confusion Matrix:
[[178   0]
 [ 22   0]]

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
rf=RandomForestClassifier(random_state=42,n_estimators=200)
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [36]:
rf_pred=rf.predict(X_test)
rf_prob=rf.predict_proba(X_test)

In [37]:
print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred)*100)
print("Random Forest Log Loss:", log_loss(y_test, rf_prob))
print("Random Forest Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

Random Forest Accuracy: 89.0
Random Forest Log Loss: 0.3639838802913989
Random Forest Confusion Matrix:
[[178   0]
 [ 22   0]]

In [38]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-macosx_12_0_arm64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.3.0-py3-none-macosx_12_0_arm64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 4.3 MB/s  0:00:00 eta 0:00:01
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0
Note: you may need to restart the kernel to use updated packages.

In [39]:
from xgboost import XGBClassifier
xgb=XGBClassifier(random_state=42, n_estimators=200,max_depth=5,learning_rate=0.1)

In [40]:
xgb.fit(X_train,y_train)
xgb_pred=xgb.predict(X_test)
xgb_prob=xgb.predict_proba(X_test)
print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred)*100)
print("XGBoost Log Loss:", log_loss(y_test, xgb_prob))
print("XGBoost Confusion Matrix:")
print(confusion_matrix(y_test, xgb_pred))

XGBoost Accuracy: 88.5
XGBoost Log Loss: 0.41124744576388844
XGBoost Confusion Matrix:
[[177   1]
 [ 22   0]]